on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

name:CI
jobs:
  write_good_job:
    runs-on:ubuntu-lastest
    permissions:
      pull-requests:write
    name:a job to lint Markdown files
    steps:
      -uses:actions/checkout@v2
      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@v1.6
      # with:
      #   directory: "manuscript" # Optional, uncomment to specify a directory to scan
    # Use the output from the `write-good` step
      - name: Get the write-good output
        run: echo "${{ steps.write-good.outputs.result }}"
      - name: Post comment
        uses: mshick/add-pr-comment@v1
        if: ${{ steps.write-good.outputs.result }}
        with:
          message: |
            ${{ steps.write-good.outputs.result }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
